#!/bin/bash

RMMOD=/sbin/rmmod

if test \! "x`type -t sudo`" = x; then
  SUDO=sudo
fi

sync

if [ "`lsmod | grep rtai`" != "" ]; then
	for MODULE in rtai_fifos rtai_mbx rtai_sem rtai_sched rtai_hal; do
		$SUDO $RMMOD $MODULE
	done
fi

sync
