function conf = crear_conf()
%CREATE_CONF Summary of this function goes here
%   Detailed explanation goes here

conf = struct( ...
    'room_dxf_file', '', ...
    'room_volume', '', ...
    'room_n_surfaces', '', ...
    'room_filter_surfaces_file', '', ...
    'ism_max_order', '', ...
    'ism_max_distance', '', ...
    'sound_source_ir_file', '', ...
    'sound_source_directivity_file', '', ...
    'sound_source_position', '', ...
    'sound_source_orientation', '', ...
    'listener_position', '', ...
    'listener_orientation', '', ...
    'listener_hrtf_file', '', ...
    'listener_filter_hrtf_file', '', ...
    'anechoic_file', '', ...
    'temperature', '', ...
    'angle_threshold', '', ...
    'bir_length', '', ...
    'master_gain_db', '' );

end

